name: MiNuevoWorkflow
on: 
  push:
    branches:
    - master      # Eventos de Push sobre el branch 'master'
  pull_request:
    branches:
    - master      # Eventos de Pull Request sobre el branch 'master'
jobs:
  build:
    name: Mi primer job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, ubuntu-18.04]
        sdk-version: ['3.0.100', '2.2.103', '2.2.103', '2.2.103']
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.sdk-version }}
    - run: dotnet publish -o app
